package com.quizapp.quiz.service;

import com.quizapp.quiz.model.Difficulty;
import com.quizapp.quiz.model.GeneratedQuestion;
import com.quizapp.quiz.model.QuizConfig;

import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Service
public class FallbackQuestionGenerator {

    public List<GeneratedQuestion> generate(QuizConfig config) {
        List<GeneratedQuestion> bank = getQuestions(config.topic(), config.difficulty());
        List<GeneratedQuestion> result = new ArrayList<>();
        for (int i = 0; i < config.numQuestions(); i++) {
            result.add(bank.get(i % bank.size()));
        }
        return result;
    }

    private List<GeneratedQuestion> getQuestions(String topic, Difficulty difficulty) {
        return switch (topic.toLowerCase()) {
            case "javascript" -> javascriptQuestions(difficulty);
            case "python" -> pythonQuestions(difficulty);
            case "java" -> javaQuestions(difficulty);
            case "web", "web dev", "webdev" -> webQuestions(difficulty);
            case "database", "databases" -> databaseQuestions(difficulty);
            case "devops" -> devopsQuestions(difficulty);
            case "algorithms" -> algorithmQuestions(difficulty);
            case "security" -> securityQuestions(difficulty);
            default -> genericQuestions(topic, difficulty);
        };
    }

    private List<GeneratedQuestion> javascriptQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is a closure in JavaScript?",
                            List.of("A function that has access to its outer scope's variables",
                                    "A way to close browser windows",
                                    "A loop termination statement",
                                    "A method to end a program"),
                            0),
                    q("Which keyword declares a block-scoped variable in JavaScript?",
                            List.of("var", "let", "global", "static"),
                            1),
                    q("What does 'typeof null' return in JavaScript?",
                            List.of("null", "undefined", "object", "boolean"),
                            2),
                    q("Which method adds an element to the end of an array?",
                            List.of("pop()", "shift()", "push()", "unshift()"),
                            2),
                    q("What is the output of '2' + 2 in JavaScript?",
                            List.of("4", "22", "NaN", "Error"),
                            1),
                    q("Which symbol is used for single-line comments in JavaScript?",
                            List.of("//", "/*", "#", "--"),
                            0)
            );
            case MEDIUM -> List.of(
                    q("What is the event loop in JavaScript?",
                            List.of("A mechanism that handles asynchronous callbacks by processing the message queue",
                                    "A for-loop that iterates over DOM events",
                                    "A method to stop code execution",
                                    "A way to loop through object properties"),
                            0),
                    q("What does the 'Promise.all()' method do?",
                            List.of("Runs promises in sequence and returns the first result",
                                    "Waits for all promises to resolve and returns an array of results",
                                    "Cancels all pending promises",
                                    "Returns a single merged promise from the last one"),
                            1),
                    q("What is the difference between '==' and '===' in JavaScript?",
                            List.of("'==' checks value only, '===' checks value and type",
                                    "'==' checks type, '===' checks value only",
                                    "They are identical in behavior",
                                    "'===' is deprecated"),
                            0),
                    q("What does 'Array.prototype.reduce()' do?",
                            List.of("Filters elements based on a condition",
                                    "Transforms each element using a callback",
                                    "Accumulates array elements into a single value",
                                    "Removes duplicates from an array"),
                            2),
                    q("What is a ' WeakRef ' in JavaScript?",
                            List.of("A reference that prevents garbage collection",
                                    "A weakly typed variable",
                                    "A reference that does not prevent garbage collection of an object",
                                    "A deprecated feature for memory leaks"),
                            2),
                    q("What does the 'async' keyword do when placed before a function?",
                            List.of("Makes the function synchronous",
                                    "Makes the function return a Promise automatically",
                                    "Prevents the function from being called",
                                    "Makes the function run in a separate thread"),
                            1)
            );
            case HARD -> List.of(
                    q("What is the time complexity of accessing an element by index in a JavaScript array?",
                            List.of("O(n)", "O(log n)", "O(1)", "O(n log n)"),
                            2),
                    q("What is the purpose of 'Object.freeze()' in JavaScript?",
                            List.of("Prevents new properties from being added",
                                    "Makes an object immutable",
                                    "Deletes all properties of an object",
                                    "Copies an object to prevent mutations"),
                            1),
                    q("Which feature allows JavaScript to handle concurrent operations on a single thread?",
                            List.of("Multi-threading", "Web Workers", "Event loop and non-blocking I/O",
                                    "Async/Await with thread pool"),
                            2),
                    q("What is a 'Proxy' in JavaScript used for?",
                            List.of("Creating network proxies",
                                    "Intercepting and customizing operations on objects",
                                    "Creating virtual DOM elements",
                                    "Managing database connections"),
                            1),
                    q("What does 'Symbol.iterator' define on an object?",
                            List.of("A unique string identifier",
                                    "A default iteration protocol for the object",
                                    "A sorting algorithm for the object",
                                    "A memory management strategy"),
                            1),
                    q("What is the difference between 'Map' and 'WeakMap' in JavaScript?",
                            List.of("Map allows keys of any type, WeakMap only allows objects as keys and does not prevent garbage collection",
                                    "Map is faster than WeakMap",
                                    "WeakMap is a deprecated version of Map",
                                    "There is no difference"),
                            0)
            );
        };
    }

    private List<GeneratedQuestion> pythonQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is a list comprehension in Python?",
                            List.of("A way to create lists using a concise syntax",
                                    "A method to sort lists",
                                    "A way to compress lists",
                                    "A loop that runs indefinitely"),
                            0),
                    q("Which keyword defines a function in Python?",
                            List.of("function", "def", "func", "define"),
                            1),
                    q("What is the output of 'print(type([]))' in Python?",
                            List.of("<class 'tuple'>", "<class 'list'>", "<class 'array'>", "<class 'set'>"),
                            1),
                    q("How do you start a comment in Python?",
                            List.of("//", "#", "/*", "--"),
                            1),
                    q("What does 'len()' do in Python?",
                            List.of("Returns the length of a sequence", "Converts to integer",
                            "Calculates logarithm", "Loops through items"),
                            0),
                    q("Which of these is a valid Python variable name?",
                            List.of("2name", "_name", "my-name", "class"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("What is a decorator in Python?",
                            List.of("A function that modifies the behavior of another function",
                                    "A comment used for documentation",
                                    "A way to import external libraries",
                                    "A type of loop"),
                            0),
                    q("What is the difference between a list and a tuple in Python?",
                            List.of("Lists are immutable, tuples are mutable",
                                    "Lists are mutable, tuples are immutable",
                                    "There is no difference",
                                    "Tuples can only hold strings"),
                            1),
                    q("What does 'yield' do in a Python generator function?",
                            List.of("Stops the function permanently",
                                    "Returns a value and pauses the function state",
                                    "Raises an exception",
                                    "Creates a new thread"),
                            1),
                    q("What is the Global Interpreter Lock (GIL) in Python?",
                            List.of("A lock that prevents multiple threads from executing Python bytecode simultaneously",
                                    "A way to secure Python scripts",
                                    "A mechanism for file locking",
                                    "A database concurrency tool"),
                            0),
                    q("What is 'self' used for in Python class methods?",
                            List.of("To create a static method",
                                    "To refer to the instance of the class",
                                    "To import modules",
                                    "To define global variables"),
                            1),
                    q("What is the output of 'bool([])' in Python?",
                            List.of("True", "False", "None", "Error"),
                            1)
            );
            case HARD -> List.of(
                    q("What is the time complexity of searching in a Python dictionary?",
                            List.of("O(n)", "O(log n)", "O(1) average", "O(n log n)"),
                            2),
                    q("What is metaclass in Python?",
                            List.of("A class that defines the behavior of other classes",
                                    "A hidden class not visible to users",
                                    "A class used for database connections",
                                    "A class that cannot be instantiated"),
                            0),
                    q("What is the purpose of '__slots__' in a Python class?",
                            List.of("To define class constants",
                                    "To restrict dynamic attribute creation and save memory",
                                    "To make all attributes private",
                                    "To enable multiple inheritance"),
                            1),
                    q("What is the difference between 'deepcopy' and 'copy' in Python?",
                            List.of("deepcopy copies references, copy creates independent objects",
                                    "copy creates independent objects, deepcopy copies references",
                                    "deepcopy recursively copies nested objects, copy only copies top-level references",
                                    "There is no difference"),
                            2),
                    q("What are 'context managers' in Python used for?",
                            List.of("Managing database connections and file I/O with guaranteed cleanup",
                                    "Managing UI windows",
                                    "Creating context-aware variables",
                                    "Handling network protocols"),
                            0),
                    q("What is the purpose of 'asyncio' in Python?",
                            List.of("Parallel CPU computation",
                                    "Writing concurrent code using async/await syntax",
                                    "Managing database transactions",
                                    "Creating GUI applications"),
                            1)
            );
        };
    }

    private List<GeneratedQuestion> javaQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is the entry point of a Java application?",
                            List.of("start() method", "main() method", "init() method", "run() method"),
                            1),
                    q("Which keyword is used to create a class in Java?",
                            List.of("struct", "class", "object", "define"),
                            1),
                    q("What does JVM stand for?",
                            List.of("Java Visual Machine", "Java Virtual Machine", "Java Variable Manager", "Java Verified Module"),
                            1),
                    q("Which of these is a valid Java data type?",
                            List.of("number", "real", "int", "decimal"),
                            2),
                    q("What is the default value of an int variable in Java?",
                            List.of("null", "1", "0", "undefined"),
                            2),
                    q("Which keyword is used to inherit a class in Java?",
                            List.of("implements", "extends", "inherits", "super"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("What is the difference between '==' and '.equals()' in Java?",
                            List.of("'==' compares references, '.equals()' compares content",
                                    "'==' compares content, '.equals()' compares references",
                                    "They are identical",
                                    "'==' is deprecated"),
                            0),
                    q("What is the purpose of the 'volatile' keyword in Java?",
                            List.of("Makes a variable thread-safe by ensuring visibility across threads",
                                    "Makes a variable immutable",
                                    "Prevents garbage collection",
                                    "Makes a variable static"),
                            0),
                    q("What is a 'Stream' in Java used for?",
                            List.of("File I/O operations only",
                                    "Functional-style operations on collections of data",
                                    "Network socket communication",
                                    "Creating user interfaces"),
                            1),
                    q("What is the difference between 'ArrayList' and 'LinkedList' in Java?",
                            List.of("ArrayList uses an array, LinkedList uses a doubly-linked list",
                                    "LinkedList is faster for random access",
                                    "ArrayList cannot grow dynamically",
                                    "There is no difference"),
                            0),
                    q("What is the purpose of 'Optional' in Java?",
                            List.of("To make variables nullable",
                                    "To explicitly represent the possibility of absence of a value",
                                    "To replace null with an empty string",
                                    "To create optional method parameters"),
                            1),
                    q("What happens when you override 'equals()' in Java?",
                            List.of("You must also override 'hashCode()' to maintain the contract",
                                    "Nothing special happens",
                                    "Java automatically overrides 'hashCode()' for you",
                                    "The JVM throws an error"),
                            0)
            );
            case HARD -> List.of(
                    q("What is the time complexity of adding an element to a PriorityQueue in Java?",
                            List.of("O(1)", "O(log n)", "O(n)", "O(n log n)"),
                            1),
                    q("What is the purpose of 'CompletableFuture' in Java?",
                            List.of("To create UI windows",
                                    "To compose and chain asynchronous computations",
                                    "To synchronize database access",
                                    "To create immutable futures"),
                            1),
                    q("What is the difference between 'ConcurrentHashMap' and 'Collections.synchronizedMap'?",
                            List.of("ConcurrentHashMap uses fine-grained locking for better concurrency",
                                    "synchronizedMap is always faster",
                                    "ConcurrentHashMap does not support null keys",
                                    "Both use the same locking mechanism"),
                            0),
                    q("What is a 'sealed class' in Java?",
                            List.of("A class that cannot be instantiated",
                                    "A class that restricts which other classes or interfaces can extend or implement it",
                                    "A class marked as final",
                                    "A class used for serialization only"),
                            1),
                    q("What is the purpose of 'record' in Java?",
                            List.of("To create mutable data carriers",
                                    "To define immutable data classes with auto-generated equals, hashCode, and toString",
                                    "To create audio records",
                                    "To record execution logs"),
                            1),
                    q("What is 'ZGC' in the Java Virtual Machine?",
                            List.of("A garbage collector designed for low latency",
                                    "A compiler optimization",
                                    "A class loader",
                                    "A debugging tool"),
                            0)
            );
        };
    }

    private List<GeneratedQuestion> webQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What does HTML stand for?",
                            List.of("Hyper Text Markup Language", "Home Tool Markup Language",
                            "Hyperlinks and Text Markup Language", "Home Text Markup Language"),
                            0),
                    q("Which CSS property controls the text color?",
                            List.of("font-color", "text-color", "color", "foreground"),
                            2),
                    q("What is the default port for HTTP?",
                            List.of("21", "80", "443", "8080"),
                            1),
                    q("Which HTML tag is used to create a hyperlink?",
                            List.of("<link>", "<a>", "<href>", "<url>"),
                            1),
                    q("What does CSS stand for?",
                            List.of("Computer Style Sheets", "Cascading Style Sheets",
                            "Colorful Style Sheets", "Creative Style System"),
                            1),
                    q("Which method is used to send data from a form in HTML?",
                            List.of("get", "post", "send", "push"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("What is the CSS Box Model?",
                            List.of("A model for creating 3D boxes",
                                    "Content, padding, border, and margin layout model",
                                    "A way to size images",
                                    "A JavaScript object model"),
                            1),
                    q("What is the difference between 'em' and 'rem' in CSS?",
                            List.of("'em' is relative to parent, 'rem' is relative to root element",
                                    "'rem' is relative to parent, 'em' is relative to root",
                                    "There is no difference",
                                    "'em' is deprecated"),
                            0),
                    q("What is CORS in web development?",
                            List.of("Cross-Origin Resource Sharing - a mechanism to allow cross-domain requests",
                                    "Common Object Request System",
                                    "A CSS framework",
                                    "A browser extension API"),
                            0),
                    q("What does 'position: sticky' do in CSS?",
                            List.of("Fixes an element at the top of the page permanently",
                                    "Makes an element stick within its container while scrolling",
                                    "Disables scrolling on the page",
                                    "Creates a sticky note effect"),
                            1),
                    q("What is the purpose of 'localStorage' in browsers?",
                            List.of("To store temporary session data",
                                    "To store key-value pairs persistently in the browser",
                                    "To communicate with a server",
                                    "To manage browser tabs"),
                            1),
                    q("What is 'debouncing' in JavaScript event handling?",
                            List.of("Executing an event handler immediately on every trigger",
                                    "Delaying execution until a specified time has passed since the last event",
                                    "Removing event listeners permanently",
                                    "Queuing events in order"),
                            1)
            );
            case HARD -> List.of(
                    q("What is the critical rendering path in browsers?",
                            List.of("The order of file loading in package.json",
                                    "The sequence of steps the browser takes to convert HTML, CSS, and JS into pixels on screen",
                                    "The path of network requests to a server",
                                    "The order of CSS property evaluation"),
                            1),
                    q("What is the Time to Interactive (TTI) metric?",
                            List.of("The time until the page is visually complete",
                                    "The time until the page is fully interactive to user input",
                                    "The time to download all resources",
                                    "The time until the DOM is ready"),
                            1),
                    q("What is the purpose of 'Content Security Policy' (CSP) in web security?",
                            List.of("To speed up page loading",
                                    "To prevent XSS and other injection attacks by controlling allowed content sources",
                                    "To encrypt all web traffic",
                                    "To manage user authentication"),
                            1),
                    q("What is the difference between HTTP/2 and HTTP/3?",
                            List.of("HTTP/3 uses QUIC/UDP instead of TCP for transport",
                                    "HTTP/3 is limited to text content only",
                                    "HTTP/2 is faster in all scenarios",
                                    "There is no meaningful difference"),
                            0),
                    q("What is 'Service Worker' in Progressive Web Apps?",
                            List.of("A server-side script that runs in the background",
                                    "A script that runs in the browser, enabling offline capabilities and background sync",
                                    "A database management tool",
                                    "A CSS preprocessor"),
                            1),
                    q("What does the 'Intersection Observer API' allow you to do?",
                            List.of("Monitor network connections",
                                    "Asynchronously observe changes in intersection of a target element with an ancestor or viewport",
                                    "Observe changes to the DOM tree",
                                    "Monitor browser memory usage"),
                            1)
            );
        };
    }

    private List<GeneratedQuestion> databaseQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What does SQL stand for?",
                            List.of("Structured Query Language", "Simple Query Language",
                            "Standard Question Language", "System Query Logic"),
                            0),
                    q("Which SQL statement is used to retrieve data from a database?",
                            List.of("GET", "RETRIEVE", "SELECT", "FETCH"),
                            2),
                    q("What is a primary key in a database?",
                            List.of("The first column of any table",
                                    "A unique identifier for each record in a table",
                                    "A password for database access",
                                    "The most important field"),
                            1),
                    q("What is the purpose of the 'WHERE' clause in SQL?",
                            List.of("To sort the results",
                                    "To filter records based on conditions",
                                    "To group records",
                                    "To delete records"),
                            1),
                    q("Which command is used to remove all records from a table but keep the structure?",
                            List.of("DELETE", "REMOVE", "TRUNCATE", "DROP"),
                            2),
                    q("What type of relationship exists when one record in a table relates to many in another?",
                            List.of("One-to-one", "One-to-many", "Many-to-many", "Zero-to-one"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("What is a database index used for?",
                            List.of("To encrypt data",
                                    "To speed up data retrieval operations",
                                    "To create backups",
                                    "To enforce data types"),
                            1),
                    q("What is the difference between INNER JOIN and LEFT JOIN?",
                            List.of("INNER JOIN returns all rows, LEFT JOIN returns matching rows only",
                                    "INNER JOIN returns matching rows from both tables, LEFT JOIN returns all rows from the left table",
                                    "There is no difference",
                                    "LEFT JOIN is faster than INNER JOIN"),
                            1),
                    q("What is database normalization?",
                            List.of("Converting all data to the same format",
                                    "Organizing data to reduce redundancy and improve data integrity",
                                    "Adding more columns to a table",
                                    "Deleting duplicate tables"),
                            1),
                    q("What is a transaction in database management?",
                            List.of("A type of join query",
                                    "A sequence of operations performed as a single logical unit of work",
                                    "A way to export data",
                                    "A query optimization technique"),
                            1),
                    q("What does 'ACID' stand for in database systems?",
                            List.of("Automatic, Concurrent, Independent, Durable",
                                    "Atomicity, Consistency, Isolation, Durability",
                                    "Access, Control, Integration, Distribution",
                                    "Automatic, Controlled, Indexed, Distributed"),
                            1),
                    q("What is the purpose of a 'foreign key' constraint?",
                            List.of("To make a column the primary key",
                                    "To enforce referential integrity between two tables",
                                    "To encrypt column data",
                                    "To make a column unique"),
                            1)
            );
            case HARD -> List.of(
                    q("What is a covering index?",
                            List.of("An index that covers all tables in a database",
                                    "An index that contains all the columns needed to satisfy a query without accessing the table data",
                                    "An index that is backed up automatically",
                                    "An index that covers only primary keys"),
                            1),
                    q("What is the CAP theorem in distributed databases?",
                            List.of("A system can simultaneously guarantee Consistency, Availability, and Partition tolerance",
                                    "A system can only guarantee two of the three: Consistency, Availability, and Partition tolerance",
                                    "A system must guarantee all three properties at all times",
                                    "A system cannot guarantee any of these properties"),
                            1),
                    q("What is optimistic concurrency control?",
                            List.of("Allowing multiple transactions to proceed without locks, checking for conflicts at commit time",
                                    "Locking all resources before a transaction begins",
                                    "Always using the latest write",
                                    "Preventing concurrent access entirely"),
                            0),
                    q("What is a materialized view?",
                            List.of("A view that is always computed on-the-fly",
                                    "A pre-computed and physically stored result set of a query",
                                    "A view that only shows material items",
                                    "A temporary table for debugging"),
                            1),
                    q("What is the purpose of 'EXPLAIN' in SQL?",
                            List.of("To execute a query",
                                    "To display the execution plan of a query",
                                    "To delete unnecessary data",
                                    "To create an index automatically"),
                            1),
                    q("What is database sharding?",
                            List.of("Deleting old data from a database",
                                    "Horizontal partitioning of data across multiple database instances",
                                    "Creating database backups",
                                    "Encrypting database files"),
                            1)
            );
        };
    }

    private List<GeneratedQuestion> devopsQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is CI/CD?",
                            List.of("Continuous Integration / Continuous Deployment - automating build, test, and release",
                                    "Computer Interface / Central Database",
                                    "Cloud Integration / Cloud Distribution",
                                    "Code Inspection / Code Debugging"),
                            0),
                    q("What is Docker primarily used for?",
                            List.of("Writing application code",
                                    "Packaging applications into containers for consistent deployment",
                                    "Managing databases",
                                    "Building user interfaces"),
                            1),
                    q("What does a version control system like Git track?",
                            List.of("Hardware performance",
                                    "Changes to files over time",
                                    "User login credentials",
                                    "Server uptime"),
                            1),
                    q("What is a deployment pipeline?",
                            List.of("A physical network cable",
                                    "An automated series of steps that software goes through from code to production",
                                    "A database migration tool",
                                    "A monitoring dashboard"),
                            1),
                    q("What is the purpose of environment variables in applications?",
                            List.of("To store source code",
                                    "To configure application behavior without changing code",
                                    "To compile applications",
                                    "To create UI themes"),
                            1),
                    q("What is 'Infrastructure as Code' (IaC)?",
                            List.of("Writing application logic in infrastructure scripts",
                                    "Managing and provisioning infrastructure through machine-readable configuration files",
                                    "Writing code directly on servers",
                                    "A programming language for networking"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("What is a Kubernetes Pod?",
                            List.of("A group of physical servers",
                                    "The smallest deployable unit in Kubernetes, containing one or more containers",
                                    "A network load balancer",
                                    "A storage volume type"),
                            1),
                    q("What is the purpose of a reverse proxy like Nginx?",
                            List.of("To directly serve web pages to users",
                                    "To forward client requests to appropriate backend servers and handle cross-cutting concerns",
                                    "To compile source code",
                                    "To manage database connections"),
                            1),
                    q("What is 'blue-green deployment'?",
                            List.of("Deploying to two different cloud providers",
                                    "Maintaining two identical production environments and switching traffic between them",
                                    "Deploying only on weekdays",
                                    "Using blue and green color themes"),
                            1),
                    q("What is the purpose of Prometheus in a DevOps stack?",
                            List.of("Managing source code repositories",
                                    "Collecting and querying metrics and time-series data from applications and infrastructure",
                                    "Building container images",
                                    "Managing secrets"),
                            1),
                    q("What is a 'sidecar' pattern in microservices?",
                            List.of("Running two services on the same server",
                                    "Deploying a helper container alongside the main application container in the same pod",
                                    "Using a backup server",
                                    "Having two separate databases"),
                            1),
                    q("What is the difference between a Docker image and a Docker container?",
                            List.of("They are the same thing",
                                    "An image is a read-only template, a container is a running instance of an image",
                                    "A container is a compressed image",
                                    "An image can only run on Linux"),
                            1)
            );
            case HARD -> List.of(
                    q("What is a service mesh like Istio used for?",
                            List.of("Building web frontends",
                                    "Managing service-to-service communication with observability, traffic management, and security",
                                    "Creating database schemas",
                                    "Compiling application code"),
                            1),
                    q("What is 'GitOps'?",
                            List.of("A way to merge Git branches automatically",
                                    "Using Git as the single source of truth for declarative infrastructure and application deployment",
                                    "A Git extension for CI/CD",
                                    "A database backup strategy"),
                            1),
                    q("What is the purpose of 'chaos engineering' (e.g., Chaos Monkey)?",
                            List.of("To prevent system failures",
                                    "To intentionally inject failures into systems to test resilience and identify weaknesses",
                                    "To monitor network traffic",
                                    "To automate code reviews"),
                            1),
                    q("What is 'canary deployment'?",
                            List.of("Deploying to a canary environment first",
                                    "Gradually rolling out changes to a small subset of users before wider deployment",
                                    "Deploying code written in the Canary language",
                                    "Using a canary token for security"),
                            1),
                    q("What is the 'four golden signals' approach in SRE monitoring?",
                            List.of("CPU, Memory, Disk, Network",
                                    "Latency, Traffic, Errors, and Saturation",
                                    "Up, Down, Warning, Critical",
                                    "Read, Write, Update, Delete"),
                            1),
                    q("What is a 'circuit breaker' pattern in distributed systems?",
                            List.of("A physical switch that shuts down servers",
                                    "A design pattern that detects failures and prevents an application from repeatedly trying to execute an operation likely to fail",
                                    "A database failover mechanism",
                                    "A load balancing algorithm"),
                            1)
            );
        };
    }

    private List<GeneratedQuestion> algorithmQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is the time complexity of binary search?",
                            List.of("O(n)", "O(log n)", "O(n^2)", "O(1)"),
                            1),
                    q("What data structure uses FIFO (First In, First Out) ordering?",
                            List.of("Stack", "Queue", "Tree", "Graph"),
                            1),
                    q("What does 'recursion' mean in programming?",
                            List.of("A loop that runs indefinitely",
                                    "A function that calls itself to solve a smaller instance of the problem",
                                    "A way to sort arrays",
                                    "A method to allocate memory"),
                            1),
                    q("What is the difference between a stack and a queue?",
                            List.of("A stack is FIFO, a queue is LIFO",
                                    "A stack is LIFO, a queue is FIFO",
                                    "Both are FIFO",
                                    "Both are LIFO"),
                            1),
                    q("What is an algorithm?",
                            List.of("A type of data structure",
                                    "A step-by-step procedure for solving a problem",
                                    "A programming language",
                                    "A hardware component"),
                            1),
                    q("What is the best-case time complexity of bubble sort?",
                            List.of("O(n^2)", "O(n log n)", "O(n)", "O(log n)"),
                            2)
            );
            case MEDIUM -> List.of(
                    q("What is the time complexity of quicksort in the average case?",
                            List.of("O(n)", "O(n log n)", "O(n^2)", "O(log n)"),
                            1),
                    q("What is a hash table used for?",
                            List.of("Sorting data alphabetically",
                                    "Providing O(1) average-case time for insertions, deletions, and lookups",
                                    "Representing hierarchical data",
                                    "Storing sorted sequences"),
                            1),
                    q("What is the difference between BFS and DFS?",
                            List.of("BFS explores level by level using a queue, DFS explores as deep as possible using a stack",
                                    "BFS uses a stack, DFS uses a queue",
                                    "BFS is always faster than DFS",
                                    "DFS explores all neighbors first"),
                            0),
                    q("What is dynamic programming?",
                            List.of("A way to write programs dynamically",
                                    "An optimization technique that solves complex problems by breaking them into overlapping subproblems and storing results",
                                    "A type of parallel programming",
                                    "A method to allocate memory dynamically"),
                            1),
                    q("What is the time complexity of merge sort?",
                            List.of("O(n)", "O(n log n)", "O(n^2)", "O(log n)"),
                            1),
                    q("What is a binary search tree (BST)?",
                            List.of("A tree where each node has exactly two children",
                                    "A tree where left child is less than parent and right child is greater",
                                    "A tree that is always balanced",
                                    "A tree with only two levels"),
                            1)
            );
            case HARD -> List.of(
                    q("What is the time complexity of Dijkstra's algorithm with a binary heap?",
                            List.of("O(V^2)", "O((V + E) log V)", "O(V log E)", "O(E log V)"),
                            1),
                    q("What is the Bellman-Ford algorithm used for?",
                            List.of("Finding the shortest path in unweighted graphs",
                                    "Finding the shortest path in graphs with negative edge weights",
                                    "Sorting arrays in O(n) time",
                                    "Detecting cycles in a graph"),
                            1),
                    q("What is the concept of 'amortized analysis'?",
                            List.of("Analyzing the worst-case cost of a single operation",
                                    "Analyzing the average cost of operations over a sequence to determine per-operation cost",
                                    "Calculating memory usage",
                                    "Estimating network latency"),
                            1),
                    q("What is the A* search algorithm?",
                            List.of("An unweighted shortest path algorithm",
                                    "A best-first search algorithm that uses a heuristic to find the shortest path efficiently",
                                    "A sorting algorithm",
                                    "A graph coloring algorithm"),
                            1),
                    q("What is the time complexity of the knapsack problem solved with dynamic programming?",
                            List.of("O(n)", "O(n * W) where W is the capacity", "O(2^n)", "O(n^2)"),
                            1),
                    q("What is the Master Theorem used for?",
                            List.of("Analyzing the performance of parallel algorithms",
                                    "Solving recurrence relations of the form T(n) = aT(n/b) + f(n) for divide-and-conquer algorithms",
                                    "Calculating the complexity of linked lists",
                                    "Determining the optimal data structure"),
                            1)
            );
        };
    }

    private List<GeneratedQuestion> securityQuestions(Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is a strong password?",
                            List.of("A password that is at least 4 characters long",
                                    "A password with a mix of uppercase, lowercase, numbers, and symbols",
                                    "A password that is a dictionary word",
                                    "A password that uses only numbers"),
                            1),
                    q("What does 'HTTPS' stand for?",
                            List.of("Hyper Text Transfer Protocol Secure", "Hyper Text Transfer Protocol Standard",
                            "Hyper Text Transfer System", "High Transfer Protocol Secure"),
                            0),
                    q("What is phishing?",
                            List.of("A type of fishing sport",
                                    "Fraudulent attempt to obtain sensitive information by impersonating a trustworthy entity",
                                    "A way to encrypt files",
                                    "A network scanning technique"),
                            1),
                    q("What is two-factor authentication (2FA)?",
                            List.of("Using two passwords",
                                    "Requiring two different forms of verification to access an account",
                                    "Logging in from two devices",
                                    "Using two browser tabs"),
                            1),
                    q("What is the purpose of a firewall?",
                            List.of("To speed up internet connections",
                                    "To monitor and control incoming and outgoing network traffic",
                                    "To store passwords",
                                    "To generate encryption keys"),
                            1),
                    q("What is a brute force attack?",
                            List.of("A physical attack on hardware",
                                    "Trying all possible combinations of passwords or keys to gain access",
                                    "A social engineering technique",
                                    "A way to optimize code"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("What is a SQL injection attack?",
                            List.of("A way to speed up SQL queries",
                                    "Inserting malicious SQL code into input fields to manipulate database queries",
                                    "A method to inject data into tables",
                                    "A technique to optimize database performance"),
                            1),
                    q("What is cross-site scripting (XSS)?",
                            List.of("A way to share scripts between websites",
                                    "Injecting malicious scripts into web pages viewed by other users",
                                    "A method to prevent script execution",
                                    "A debugging technique for web apps"),
                            1),
                    q("What is the purpose of salting in password hashing?",
                            List.of("To make passwords taste better",
                                    "To add random data to a password before hashing to prevent rainbow table attacks",
                                    "To compress password storage",
                                    "To speed up password verification"),
                            1),
                    q("What is a CSRF attack?",
                            List.of("A way to cache server responses",
                                    "Forcing an authenticated user to execute unwanted actions on a web application",
                                    "A method to encrypt network traffic",
                                    "A technique to improve server performance"),
                            1),
                    q("What is the principle of least privilege?",
                            List.of("Giving users the least amount of information possible",
                                    "Granting only the minimum levels of access or permissions needed to perform a task",
                                    "Using the least powerful encryption",
                                    "Restricting all access by default"),
                            1),
                    q("What is OWASP?",
                            List.of("A web browser extension",
                                    "An open-source foundation focused on improving software security",
                                    "A programming language",
                                    "A database management system"),
                            1)
            );
            case HARD -> List.of(
                    q("What is a zero-day vulnerability?",
                            List.of("A vulnerability that exists for exactly one day",
                                    "A security flaw unknown to the vendor or for which no patch exists",
                                    "A vulnerability that only affects zero users",
                                    "A fixed vulnerability"),
                            1),
                    q("What is the difference between symmetric and asymmetric encryption?",
                            List.of("Symmetric uses one key for both encryption and decryption, asymmetric uses a public-private key pair",
                                    "Asymmetric uses one key, symmetric uses two",
                                    "There is no practical difference",
                                    "Symmetric is only used for hashing"),
                            0),
                    q("What is a side-channel attack?",
                            List.of("An attack on a backup server",
                                    "Exploiting information leaked through physical implementation rather than algorithmic weaknesses",
                                    "An attack using a secondary network channel",
                                    "A method to intercept DNS queries"),
                            1),
                    q("What is a buffer overflow attack?",
                            List.of("Adding extra data to a buffer to crash the system",
                                    "Writing data beyond the bounds of allocated memory to execute arbitrary code",
                                    "Filling a buffer with random data",
                                    "A way to optimize memory usage"),
                            1),
                    q("What is the purpose of a 'honeypot' in cybersecurity?",
                            List.of("To store sensitive data securely",
                                    "A decoy system designed to attract and detect unauthorized access attempts",
                                    "To speed up authentication",
                                    "To encrypt web traffic"),
                            1),
                    q("What is certificate pinning?",
                            List.of("Saving a certificate to the desktop",
                                    "Associating a specific certificate or public key with a particular server to prevent MITM attacks",
                                    "Pinning certificates physically on servers",
                                    "A way to revoke certificates"),
                            1)
            );
        };
    }

    private List<GeneratedQuestion> genericQuestions(String topic, Difficulty difficulty) {
        return switch (difficulty) {
            case EASY -> List.of(
                    q("What is the most fundamental concept in " + topic + "?",
                            List.of("Understanding basic principles and terminology",
                                    "Advanced optimization techniques",
                                    "Complex algorithmic thinking",
                                    "Memory management at the hardware level"),
                            0),
                    q("Which practice is essential when learning " + topic + "?",
                            List.of("Skipping all documentation",
                                    "Building a strong foundation of core concepts",
                                    "Only using the most complex tools",
                                    "Avoiding hands-on practice"),
                            1),
                    q("What should a beginner focus on first in " + topic + "?",
                            List.of("Contributing to open source immediately",
                                    "Learning the basic building blocks and terminology",
                                    "Building a complete production system",
                                    "Memorizing advanced techniques"),
                            1)
            );
            case MEDIUM -> List.of(
                    q("Which approach best demonstrates intermediate understanding of " + topic + "?",
                            List.of("Ignoring established patterns and practices",
                                    "Applying standard industry conventions and best practices",
                                    "Only using theoretical knowledge",
                                    "Avoiding documentation and testing"),
                            1),
                    q("What is the primary goal of applying " + topic + " principles to real problems?",
                            List.of("To make problems harder",
                                    "To solve problems more effectively using proven approaches",
                                    "To avoid thinking about solutions",
                                    "To create unnecessary complexity"),
                            1),
                    q("What does a solid intermediate-level approach to " + topic + " rely on?",
                            List.of("Pure luck and guesswork",
                                    "Established guidelines and practical experience",
                                    "Avoiding all established tools",
                                    "Using only the latest experimental features"),
                            1)
            );
            case HARD -> List.of(
                    q("What distinguishes expert-level " + topic + " practice from intermediate?",
                            List.of("Always choosing the most complex solution available",
                                    "Understanding trade-offs and choosing deliberately based on context",
                                    "Copying solutions without analysis",
                                    "Avoiding all optimization"),
                            1),
                    q("When is a sophisticated solution in " + topic + " appropriate?",
                            List.of("When it solves the problem without introducing unnecessary complexity",
                                    "Always, regardless of the problem requirements",
                                    "When it makes the code harder to read and maintain",
                                    "Never, simple solutions are always superior"),
                            0),
                    q("What is the most important skill for advanced " + topic + " practitioners?",
                            List.of("Memorizing every API and function available",
                                    "Understanding underlying principles and adapting to new situations",
                                    "Using the most tools and libraries",
                                    "Writing the most code possible"),
                            1)
            );
        };
    }

    private GeneratedQuestion q(String question, List<String> options, int correctIndex) {
        return new GeneratedQuestion(question, List.copyOf(options), options.get(correctIndex));
    }
}
