spring.application.name=quiz
spring.application.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/scoresDB
spring.datasource.username=postgres
spring.datasource.password=7979
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

app.quiz.ai.model=gemini-3.5-flash
app.quiz.ai.force-fallback=true
